groups:
- name: heapmate
  jobs:
  - build-and-push
  - deploy-eudc01-tkg-shared-np

jobs:
- name: build-and-push
  plan:
  - in_parallel:
      steps:
      - get: heapmate-source-code
      - get: version
  - put: push-docker-image
    resource: heapmate-docker-image
    params:
      build: heapmate-source-code
      dockerfile: heapmate-source-code/heapmate/Dockerfile
      tag: version/version

resources:
- name: heapmate-source-code
  type: git
  source:
    uri: https://gitlab.axadmin.net/DevOps/tkg/automation/heapmate.git
    username: ((gitlab-user))
    password: ((gitlab-password))

- name: version
  type: semver
  source:
    driver: git
    uri: https://gitlab.axadmin.net/DevOps/tkg/automation/heapmate.git
    username: ((gitlab-user))
    password: ((gitlab-password))
    branch: version
    file: version

- name: heapmate-docker-image
  type: docker-image
  source:
    repository: feeds-emea.axadmin.net/devops/go/heapmate
    username: ((proget-user))
    password: ((proget-password))
