replicaCount: 1

image:
  repository: feeds-emea.axadmin.net/devops/java/heapmate
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: heapmate.tkg-shared-dev.eudc01.solera.farm

resources: 
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
